# Generated by Django 5.2.6 on 2025-10-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Moddle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('position', models.CharField(choices=[('guard', 'Guard'), ('cleaner', 'Cleaner'), ('engineer', 'Engineer'), ('manager', 'Manager'), ('other', 'Other')], db_index=True, default='other', verbose_name='Position')),
                ('hired_date', models.DateField(auto_now_add=True, verbose_name='Date of employment')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date deleted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='User created the employee record')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['position'], name='workers_wor_positio_86a69d_idx'), models.Index(fields=['is_active'], name='workers_wor_is_acti_bfc83b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('position__in', ['guard', 'cleaner', 'engineer', 'manager', 'other'])), name='workers_worker_position_valid')],
            },
        ),
    ]
