# Generated by Django 5.2.6 on 2025-10-18 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['email'], name='workers_wor_email_af9293_idx'),
        ),
    ]
